### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by cbracco** [BovAcademy-opensource/seed-ui#1]
Once this thing gets closer to an official release, could be useful to introduce some sort of versioning. Many folks in open-source use semantic versioning: http://semver.org/

**Comment by Gruximillian** [comment]
Of course, we should use some versioning convention.

**Comment by GabrieleRomeo** [comment]
I'm for the semantic versioning. Good idea @cbracco 👍

**Comment by brianhernandez** [comment]
Yea, sounds good.

**Comment by escorponox** [comment]
We should use semver. But we should use hash for file caching, I know how to setup `gulp-rev` we can migrate to gulp after the release if you agree.

**Comment by Gruximillian** [comment]
@escorponox 
> We should use semver. But we should use hash for file caching, I know how to setup gulp-rev we can migrate to gulp after the release if you agree.

Can you explain a bit more this part "But we should use hash for file caching", I don't know wht you mean.
Also, I've herad that Gulp is better that Grunt, so I agree to migrate to Gulp later on.

**Comment by Gruximillian** [comment]
I'm not sure how would we go about using semver. We have to have some kind of API and dependency list etc. Only thing that we depend on now normalize.css and some node packages for build process.
If anyone has a clear idea how to use semver properly, let's hear it.
