### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cbracco** [BovAcademy-opensource/seed-ui#3]
We should choose a license for this open source project. I typically go with the [MIT License](https://opensource.org/licenses/MIT), but we will probably have to use whatever Bov wants to use.

**Comment by escorponox** [comment]
I agree with you. Go MIT or whatever Richard wants. I really have no idea about FOS licenses

**Comment by Gruximillian** [comment]
@cbracco @escorponox 
I think that Richard said that we are free to choose the license, so whatever you decide is fine.

**Comment by GabrieleRomeo** [comment]
Go with MIT

**Comment by brianhernandez** [comment]
Yea, I think MIT license is probably fine.  I'd like more time to read more about these things... but I'm comforted in the fact that so many things use the MIT license.

**Comment by Gruximillian** [comment]
I agree to use MIT. It sounds reasonable.

**Comment by GabrieleRomeo** [comment]
We have already a license. So, I close this issue.
