### ISSUE TITLE
Contributing Guidelines?

### ISSUE THREAD

**Issue by cbracco** [BovAcademy-opensource/seed-ui#4]
Typically its a good idea to provide instructions for developers who may want to make contributions to the project. Here is a good article about setting guidelines: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by GabrieleRomeo** [comment]
I like it @cbracco

**Comment by GabrieleRomeo** [comment]
We have already a guideline. So, I close this issue.
