### ISSUE TITLE
Switch to a professional Workflow

### ISSUE THREAD

**Issue by GabrieleRomeo** [BovAcademy-opensource/seed-ui#6]
Since our project could increase a lot, I think we have to figure out an appropriate Workflow.

We cannot run the risk of breaking the official release through unwanted changes from a contributor which can push directly to the master.

What do you think about the **Gitflow** https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow

In a nutshell, its aim is to separate the *official* release (which lives into the *master* branch) from an 
an integration branch (tipically called the *develop* branch).

Here it's explain even more better: https://leanpub.com/git-flow/read

**Comment by escorponox** [comment]
I'm a big fan of this

**Comment by brianhernandez** [comment]
Yea, this seems great.  It's my understanding that this is how it's done in professional settings and it would be good for us to start working as the professionals do.

**Comment by escorponox** [comment]
We can keep working the same way until the release  and then freeze `master` and create the `develop` branch

**Comment by escorponox** [comment]
We are already using workflow so I'm closing this
