### ISSUE TITLE
Remind people to switch to the development branch when following guide

### ISSUE THREAD

**Issue by NathanJPlummer** [BovAcademy-opensource/seed-ui#77]
In the README:

>Use Bundler to install all required Ruby gems (the Ruby equivalent of “packages”) specific to the showcase website (located in the /docs directory) by running the following command(s):

*Add this:* git checkout development

>cd docs/
>gem install bundler
>bundle install
>NOTE: You only need to run gem bundler install if you didn’t already install Bundler on your machine in >the previous steps.

It seems obvious, but when following the guide step by step it's easy to forget you need to move to the development branch.

**Comment by Gruximillian** [comment]
@NathanJPlummer 

Done. Thanks!
